@include('assets.css')
<div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    @include('layouts.owner.header')
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
        <!-- partial -->
        <!-- partial:partials/_sidebar.html -->
        @include('layouts.owner.sidebar')
        <!-- partial -->
        <div class="main-panel">
            <div class="content-wrapper p-4">
                <!-- Greeting -->
                <div class="row">

                    <div class="col-12 grid-margin stretch-card">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Create New Rental Agreement</h4>
                                <p class="card-description">
                                    Register a new vehicle rental or lease-to-own agreement. The agreement will start with status <strong>“Created”</strong> by default.
                                </p>

                                <form class="forms-sample">

                                    <!-- AGREEMENT INFORMATION -->
                                    <h4 class="card-title mt-3 text-primary">Agreement Information</h4>
                                    <div class="row mt-2">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="agreementNumber">Agreement Number</label>
                                                <input type="text" class="form-control" id="agreementNumber" name="agreement_number" value="AG-{{ date('Y') }}-001" readonly>
                                                <small class="text-muted">Automatically generated by system.</small>
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="agreementDate">Agreement Date</label>
                                                <input type="date" class="form-control" id="agreementDate" name="agreement_date" value="{{ date('Y-m-d') }}">
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="rentalType">Rental Type</label>
                                                <select class="form-select form-control" id="rentalType" name="rental_type">
                                                    <option value="">Select Type</option>
                                                    <option value="daily">Daily</option>
                                                    <option value="weekly">Weekly</option>
                                                    <option value="monthly">Monthly</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- VEHICLE DETAILS -->
                                    <h4 class="card-title mt-4 text-primary">Vehicle Details</h4>
                                    <div class="row mt-2">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="vehicleNumber">Vehicle Plate Number</label>
                                                <input type="text" class="form-control" id="vehicleNumber" name="vehicle_number" placeholder="e.g. T 456 ABC">
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="vehicleModel">Vehicle Model</label>
                                                <input type="text" class="form-control" id="vehicleModel" name="vehicle_model" placeholder="e.g. Bajaj RE / Toyota Axio">
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="vehicleType">Vehicle Type</label>
                                                <select class="form-select form-control" id="vehicleType" name="vehicle_type">
                                                    <option value="">Select Type</option>
                                                    <option>Sedan</option>
                                                    <option>Hatchback</option>
                                                    <option>Van</option>
                                                    <option>Truck</option>
                                                    <option>Bus</option>
                                                    <option>Motorbike</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- OWNERSHIP INFORMATION -->
                                    <h4 class="card-title mt-4 text-primary">Ownership & Capacity</h4>
                                    <div class="row mt-2">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="ownerName">Owner Name</label>
                                                <input type="text" class="form-control" id="ownerName" name="owner_name" placeholder="e.g. John Doe">
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label for="capacity">Seating / Carrying Capacity</label>
                                                <input type="text" class="form-control" id="capacity" name="capacity" placeholder="e.g. 4 Passengers">
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label for="registrationDate">Vehicle Registration Date</label>
                                                <input type="date" class="form-control" id="registrationDate" name="registration_date">
                                            </div>
                                        </div>
                                    </div>

                                    <!-- FINANCIAL TERMS -->
                                    <h4 class="card-title mt-4 text-primary">Financial & Payment Terms</h4>
                                    <div class="row mt-2">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="rentalRate">Rental Rate (TZS)</label>
                                                <input type="number" class="form-control" id="rentalRate" name="rental_rate" placeholder="e.g. 30,000">
                                                <small class="text-muted">Rate per term (day/week/month depending on rental type).</small>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="rentalDuration">Rental Duration</label>
                                                <input type="number" class="form-control" id="rentalDuration" name="rental_duration" placeholder="e.g. 90 (days)">
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="totalAmount">Total Rental / Loan Amount (TZS)</label>
                                                <input type="number" class="form-control" id="totalAmount" name="total_amount" placeholder="Auto-calculated">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row mt-3">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="paymentMode">Payment Mode</label>
                                                <select class="form-select form-control" id="paymentMode" name="payment_mode">
                                                    <option value="">Select Mode</option>
                                                    <option>Mobile Money</option>
                                                    <option>Cash</option>
                                                    <option>Bank Transfer</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="leaseType">Lease Type</label>
                                                <select class="form-select form-control" id="leaseType" name="lease_type">
                                                    <option value="">Select Type</option>
                                                    <option>Standard Rental</option>
                                                    <option>Lease-to-Own</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="initialDeposit">Initial Deposit (TZS)</label>
                                                <input type="number" class="form-control" id="initialDeposit" name="initial_deposit" placeholder="e.g. 100,000">
                                            </div>
                                        </div>
                                    </div>

                                    <!-- AGREEMENT TIMELINE -->
                                    <h4 class="card-title mt-4 text-primary">Agreement Duration</h4>
                                    <div class="row mt-2">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="startDate">Start Date</label>
                                                <input type="date" class="form-control" id="startDate" name="start_date">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="endDate">Expected End Date</label>
                                                <input type="date" class="form-control" id="endDate" name="end_date">
                                            </div>
                                        </div>
                                    </div>

                                    <!-- VEHICLE DOCUMENTS -->
                                    <h4 class="card-title mt-4 text-primary">Vehicle Documents</h4>
                                    <div class="row mt-2">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Logbook (Upload)</label>
                                                <input type="file" name="logbook" class="file-upload-default">
                                                <div class="input-group">
                                                    <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Logbook">
                                                    <button class="file-upload-browse btn btn-primary" type="button">Browse</button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Insurance (Upload)</label>
                                                <input type="file" name="insurance" class="file-upload-default">
                                                <div class="input-group">
                                                    <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Insurance">
                                                    <button class="file-upload-browse btn btn-primary" type="button">Browse</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- ADDITIONAL TERMS -->
                                    <h4 class="card-title mt-4 text-primary">Terms & Remarks</h4>
                                    <div class="form-group mt-2">
                                        <label for="remarks">Additional Notes or Terms</label>
                                        <textarea class="form-control" id="remarks" name="remarks" rows="4"
                                                  placeholder="e.g. Late payment incurs a daily penalty of 2,000 TZS. Driver responsible for maintenance."></textarea>
                                    </div>

                                    <!-- SUBMIT -->
                                    <div class="mt-4">
                                        <button type="submit" class="btn btn-primary me-2">Create Agreement</button>
                                        <button type="reset" class="btn btn-light">Cancel</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- content-wrapper ends -->
            <!-- partial:partials/_footer.html -->
            @include('layouts.footer')
            <!-- partial -->
        </div>
        <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->


@include('assets.js')


