@include('assets.css')
<div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    @include('layouts.owner.header')
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
        <!-- partial -->
        <!-- partial:partials/_sidebar.html -->
        @include('layouts.owner.sidebar')
        <!-- partial -->
        <div class="main-panel">
            <div class="content-wrapper p-4">
                <!-- Greeting -->
                <div class="row">
                    <div class="col-12">
                        <div class="card shadow-sm border-0 rounded-3">
                            <div class="card-body">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                    <h4 class="card-title text-primary mb-0">
                                        <i class="mdi mdi-file-chart"></i> Reports
                                    </h4>
                                    <button class="btn btn-primary btn-sm">
                                        <i class="mdi mdi-download"></i> Export All Reports
                                    </button>
                                </div>

                                <div class="table-responsive mt-4">
                                    <table id="reportsTable" class="table table-hover align-middle text-center">
                                        <thead class="bg-primary text-white">
                                        <tr>
                                            <th>#</th>
                                            <th>Report Name</th>
                                            <th>Report Type</th>
                                            <th>Description</th>
                                            <th>Generated By</th>
                                            <th>Generated On</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <!-- Sample Data -->
                                        <tr>
                                            <td>1</td>
                                            <td>Vehicle Summary Report</td>
                                            <td>Fleet</td>
                                            <td>Overview of all registered vehicles, including type, capacity, and status.</td>
                                            <td>Admin</td>
                                            <td>04 Nov 2025</td>
                                            <td>
                                                <button class="btn btn-outline-primary btn-sm me-1" title="View Report">
                                                    <i class="mdi mdi-eye"></i>
                                                </button>
                                                <button class="btn btn-outline-success btn-sm" title="Download PDF">
                                                    <i class="mdi mdi-download"></i>
                                                </button>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>2</td>
                                            <td>Driver Performance Report</td>
                                            <td>Driver</td>
                                            <td>Details driver assignments, number of trips, earnings, and penalties.</td>
                                            <td>Manager</td>
                                            <td>04 Nov 2025</td>
                                            <td>
                                                <button class="btn btn-outline-primary btn-sm me-1" title="View Report">
                                                    <i class="mdi mdi-eye"></i>
                                                </button>
                                                <button class="btn btn-outline-success btn-sm" title="Download PDF">
                                                    <i class="mdi mdi-download"></i>
                                                </button>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>3</td>
                                            <td>Owner Revenue Report</td>
                                            <td>Owner</td>
                                            <td>Shows total income, outstanding balances, and total vehicles per owner.</td>
                                            <td>Finance</td>
                                            <td>03 Nov 2025</td>
                                            <td>
                                                <button class="btn btn-outline-primary btn-sm me-1" title="View Report">
                                                    <i class="mdi mdi-eye"></i>
                                                </button>
                                                <button class="btn btn-outline-success btn-sm" title="Download PDF">
                                                    <i class="mdi mdi-download"></i>
                                                </button>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>4</td>
                                            <td>Payment History Report</td>
                                            <td>Financial</td>
                                            <td>Summarizes all payments received, missed, and upcoming due payments.</td>
                                            <td>Accountant</td>
                                            <td>02 Nov 2025</td>
                                            <td>
                                                <button class="btn btn-outline-primary btn-sm me-1" title="View Report">
                                                    <i class="mdi mdi-eye"></i>
                                                </button>
                                                <button class="btn btn-outline-success btn-sm" title="Download PDF">
                                                    <i class="mdi mdi-download"></i>
                                                </button>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>5</td>
                                            <td>Loan Status Report</td>
                                            <td>Finance</td>
                                            <td>Displays active, cleared, and overdue loans linked to vehicle agreements.</td>
                                            <td>Finance Manager</td>
                                            <td>01 Nov 2025</td>
                                            <td>
                                                <button class="btn btn-outline-primary btn-sm me-1" title="View Report">
                                                    <i class="mdi mdi-eye"></i>
                                                </button>
                                                <button class="btn btn-outline-success btn-sm" title="Download PDF">
                                                    <i class="mdi mdi-download"></i>
                                                </button>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>6</td>
                                            <td>Agreement Summary Report</td>
                                            <td>Agreements</td>
                                            <td>Lists all active agreements with duration, payment progress, and end date.</td>
                                            <td>Admin</td>
                                            <td>31 Oct 2025</td>
                                            <td>
                                                <button class="btn btn-outline-primary btn-sm me-1" title="View Report">
                                                    <i class="mdi mdi-eye"></i>
                                                </button>
                                                <button class="btn btn-outline-success btn-sm" title="Download PDF">
                                                    <i class="mdi mdi-download"></i>
                                                </button>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>7</td>
                                            <td>Maintenance & Repairs Report</td>
                                            <td>Fleet</td>
                                            <td>Tracks repair and maintenance costs for each vehicle and their frequency.</td>
                                            <td>Operations</td>
                                            <td>30 Oct 2025</td>
                                            <td>
                                                <button class="btn btn-outline-primary btn-sm me-1" title="View Report">
                                                    <i class="mdi mdi-eye"></i>
                                                </button>
                                                <button class="btn btn-outline-success btn-sm" title="Download PDF">
                                                    <i class="mdi mdi-download"></i>
                                                </button>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>8</td>
                                            <td>Defaulters Report</td>
                                            <td>Financial</td>
                                            <td>Lists customers or drivers with overdue payments or agreement breaches.</td>
                                            <td>Credit Control</td>
                                            <td>30 Oct 2025</td>
                                            <td>
                                                <button class="btn btn-outline-primary btn-sm me-1" title="View Report">
                                                    <i class="mdi mdi-eye"></i>
                                                </button>
                                                <button class="btn btn-outline-success btn-sm" title="Download PDF">
                                                    <i class="mdi mdi-download"></i>
                                                </button>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>


            </div>
            <!-- content-wrapper ends -->
            <!-- partial:partials/_footer.html -->
            @include('layouts.footer')
            <!-- partial -->
        </div>
        <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->


@include('assets.js')



<script>
    $(document).ready(function() {
        $('#reportsTable').DataTable({
            pageLength: 5,
            order: [[0, 'asc']],
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search drivers..."
            }
        });
    });
</script>
